name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Archive Web Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: build/web
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - run: flutter pub get
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Archive Android Artifact
      uses: actions/upload-artifact@master
      with:
        name: android-build
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows
    - name: Archive Windows Artifact
      uses: actions/upload-artifact@master
      with:
        name: windows-build
        path: build/windows/runner/Release
